version: "3.8"

services:
  ollama:
    build: ./ollama
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"

  fastapi-app:
    build: ./app
    container_name: fastapi-app
    depends_on:
      - ollama
    ports:
      - "5005:5005"
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    restart: always

volumes:
  ollama-data:
