# In docker-compose.yml
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./app:/app
    networks:
      - chatbot-net
    command: uvicorn api:app --host '0.0.0.0' --port 5005  # Change this line
